library(ggplot2)
library(readr)
library(MASS)
library(standardize)
library("FactoMineR")
library("factoextra")

#library(score)
NTR <- read.table("E:/Master Documents/Multivariate Statistical Methods/Assignment01/T1-9.dat")
n <- ncol(NTR) 
NTR_Par <- as.matrix(NTR[,2: n])
colnames(NTR_Par) <- c("100m", "200m","400m","800m","1500m","3000m","Marathon")
print(cor_NTR <- cor(NTR_Par))
eigen(cor_NTR)
summary(NTR_Par)
res_pca <- PCA(NTR_Par , graph = FALSE)
eig.val <- get_eig(res_pca)
eig.val
fviz_eig(res_pca,addlabels = TRUE , ylim = c(0,50) )
